# Generated by Django 4.1.2 on 2022-11-03 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_created_at_application_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
