# Generated by Django 4.1.2 on 2022-11-03 02:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_rename_comapany_company"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("Front-End", "Front"),
                    ("Back-End", "Back"),
                    ("Full-Stack", "Full"),
                    ("Não definido", "Default"),
                ],
                default="Não definido",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="comapany",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="companies.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="contract",
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="estimated_pay",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="level",
            field=models.CharField(
                choices=[
                    ("Estágio", "Intern"),
                    ("Treinee", "Trainee"),
                    ("Júnior", "Junior"),
                    ("Pleno", "Mid"),
                    ("Sênior", "Senior"),
                    ("Não definido", "Default"),
                ],
                default="Não definido",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="period",
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="url",
            field=models.CharField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
