# Generated by Django 4.1.2 on 2022-11-01 13:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comapany",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comapany",
            name="name",
            field=models.CharField(
                default="<function now at 0x000002030A0081F0>",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comapany",
            name="segment",
            field=models.CharField(default="deafult", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comapany",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
