# Generated by Django 4.1.2 on 2022-11-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0002_comapany_description_comapany_name_comapany_segment_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comapany",
            new_name="Company",
        ),
    ]
