# Generated by Django 4.1.2 on 2022-11-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Intervew",
            new_name="Interview",
        ),
    ]
