# Generated by Django 4.1.3 on 2022-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="passed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
